# Generated by Django 3.1.6 on 2021-04-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default=2, verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
