# Generated by Django 3.1.6 on 2021-04-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
    ]
